/**********************************************************************
Copyright (C) 2004 by Chris Morley for template
Copyright (C) 2017 by Ben Bucior for Systre format

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
***********************************************************************/

#include <openbabel/babelconfig.h>
#include <openbabel/obmolecformat.h>

using namespace std;

// See http://openbabel.org/docs/dev/WritePlugins/AddFileFormat.html for more help
namespace OpenBabel
{

class SystreFormat : public OBMoleculeFormat
// Derive directly from OBFormat for objects which are not molecules.
{
public:
	//Register this format type ID in the constructor
  SystreFormat()
	{
		OBConversion::RegisterFormat("CGD",this);
		OBConversion::RegisterOptionParam("c", this, 0, OBConversion::OUTOPTIONS);
	}

	/* The first line of the description should be a brief identifier, <40 chars, because
     it is used in dropdown lists, etc. in some user interfaces. The rest is optional.

	   Describe any format specific options here. This text is parsed to provide
	   checkboxes, etc for the GUI (for details click the control menu),
	   so please try to keep to a similar form.

	   Write options are the most common, and the "Write" is optional.
	   The option f takes a text parameter, so that it is essential that the option
	   is registered in the constructor of the class.
	   Finish the options with a blank line as shown, if there are more than one
	   group of options, or if there are further comments after them.
	*/
	virtual const char* Description() //required
	{
		return
		"CGD format for Systre networks\n"
		"Topological network with vertices (atoms) and edges (bonds)\n"
		"Write Options e.g. -xc \n"
		"	c  Write optional edge center coordinates\n"
		;
	};

	virtual const char* SpecificationURL(){return
     "http://gavrog.org/Systre-Help.html#file_formats";};

  virtual unsigned int Flags()
  {
      return NOTREADABLE | WRITEONEONLY;
  };

 	/* This optional function is for formats which can contain more than one
	   molecule. It is used to quickly position the input stream after the nth
	   molecule without have to convert and discard all the n molecules.
	   See obconversion.cpp for details and mdlformat.cpp for an example.*/
	virtual int SkipObjects(int n, OBConversion* pConv)
	{
		return 0;
	};

	////////////////////////////////////////////////////
  /// Declarations for the "API" interface functions. Definitions are below
  // virtual bool ReadMolecule(OBBase* pOb, OBConversion* pConv);
  virtual bool WriteMolecule(OBBase* pOb, OBConversion* pConv);

private:
	/* Add declarations for any local function or member variables used.
	   Generally only a single instance of a format class is used. Keep this in
	   mind if you employ member variables. */
};
	////////////////////////////////////////////////////

//Make an instance of the format class
SystreFormat theSystreFormat;

////////////////////////////////////////////////////////////////

bool SystreFormat::WriteMolecule(OBBase* pOb, OBConversion* pConv)
{
	OBMol* pmol = dynamic_cast<OBMol*>(pOb);
	if(pmol==NULL)
		return false;

	ostream& ofs = *pConv->GetOutStream();

	/** Write the representation of the OBMol molecule to the output stream **/

	//To use an output option

	bool print_edge_centers = false;
	if(!pConv->IsOption("c")) //OBConversion::OUTOPTIONS is the default
		print_edge_centers = true;

	ofs << "# CGD file generated by Open Babel " << BABEL_VERSION << ", see http://openbabel.sf.net" << endl;
	// OTHER OUTPUT STUFF GOES HERE

	return true;
} //WriteMolecule

} //namespace OpenBabel

