// See https://openbabel.org/docs/dev/UseTheLibrary/CppExamples.html
// Get iterator help from http://openbabel.org/dev-api/group__main.shtml
// Visualize with http://baoilleach.webfactional.com/site_media/blog/emscripten/openbabel/webdepict.html

// Instead of including code to display the full MOF SMILES, just use openbabel natively:
// obabel CIFFILE -ap -ocan

#include <iostream>
#include <sstream>
#include <algorithm>
#include <stdio.h>
#include <stdlib.h>
#include <openbabel/obconversion.h>
#include <openbabel/mol.h>
#include <openbabel/obiter.h>


using namespace OpenBabel;  // See http://openbabel.org/dev-api/namespaceOpenBabel.shtml

// Function prototypes
bool readCIF(OBMol* molp, std::string filepath);
void writeCIF(OBMol* molp, std::string filepath, bool write_bonds = true);
void printFragments(const std::vector<std::string> &unique_smiles);
std::vector<std::string> uniqueSMILES(std::vector<OBMol> fragments, OBConversion obconv);
bool isMetal(const OBAtom* atom);
void resetBonds(OBMol *mol);
bool subtractMols(OBMol *mol, OBMol *subtracted);
int deleteBonds(OBMol *mol, bool only_metals = false);
bool atomsEqual(const OBAtom &atom1, const OBAtom &atom2);
OBAtom* atomInOtherMol(OBAtom *atom, OBMol *mol);
int collapseSBU(OBMol *mol, OBMol *fragment);
vector3 getCentroid(OBMol *fragment, bool weighted);


template<typename T>  // WARNING: look out for linker complications: https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl
bool inVector(const T &element, const std::vector<T> &vec) {
	// Test if an element is a given member of a vector
	if (std::find(vec.begin(), vec.end(), element) != vec.end()) {  // idiomatic C++
		return true;
	} else {
		return false;
	}
}


/* Constants */
const bool EXPORT_NODES = true;
std::string connection = "Og";  // for now, use Oganesson (118) as an indicator for MOF connections


int main(int argc, char* argv[])
{
	obErrorLog.SetOutputLevel(obInfo);  // See also http://openbabel.org/wiki/Errors
	char* filename;
	filename = argv[1];  // TODO: Check usage later

	OBMol mol;
	if (!readCIF(&mol, filename)) {
		printf("Error reading file: %s", filename);
		exit(1);
	}
	OBMol orig_mol = mol;  // Copy original definition to another variable for later use

	// Find linkers by deleting bonds to metals
	std::vector<OBMol> fragments;
	deleteBonds(&mol, true);
	fragments = mol.Separate();

	OBConversion obconv;
	obconv.SetOutFormat("can");
	obconv.AddOption("i");  // Ignore SMILES chirality for now

	// Get a list of unique SMILES code
	std::vector<std::string> unique_smiles = uniqueSMILES(fragments, obconv);
	std::stringstream fragmentMsg;
	fragmentMsg << "Unique fragments detected:" << std::endl;
	for (std::vector<std::string>::const_iterator i2 = unique_smiles.begin(); i2 != unique_smiles.end(); ++i2) {
		fragmentMsg << *i2;
	}
	obErrorLog.ThrowError(__FUNCTION__, fragmentMsg.str(), obDebug);

	// Classify nodes and linkers based on composition.
	// Consider all single atoms and hydroxyl species as node building materials.
	OBMol nodes = orig_mol;
	OBMol linkers = orig_mol;  // Can't do this by additions, because we need the UC data, etc.
	OBMol simplified_net = orig_mol;
	nodes.BeginModify();
	linkers.BeginModify();
	simplified_net.BeginModify();
	std::stringstream nonmetalMsg;
	for (std::vector<OBMol>::iterator it = fragments.begin(); it != fragments.end(); ++it) {
		OBMol canon = *it;
		resetBonds(&canon);
		std::string mol_smiles = obconv.WriteString(&canon);
		// printf(mol_smiles.c_str());
		if (it->NumAtoms() == 1) {
			nonmetalMsg << "Found a solitary atom with atomic number " << it->GetFirstAtom()->GetAtomicNum() << std::endl;
			subtractMols(&linkers, &*it);
		} else if (mol_smiles == "[OH]\t\n") {
			// Tab is generated by the SMILES vs. name part of the string
			nonmetalMsg << "Found a hydroxyl group" << std::endl;
			subtractMols(&linkers, &*it);
		} else if (mol_smiles == "O\t\n") {
			nonmetalMsg << "Found a bound water molecule" << std::endl;
			subtractMols(&linkers, &*it);
		} else {
			nonmetalMsg << "Deleting linker " << mol_smiles;
			subtractMols(&nodes, &*it);
			collapseSBU(&simplified_net, &*it);
		}
	}
	obErrorLog.ThrowError(__FUNCTION__, nonmetalMsg.str(), obDebug);
	// TODO: Need to combine the SBUs also at the end.  Do this by combining all of the &nodes fragments??
	// Also think about where this should happen wrt EndModify()
	nodes.EndModify();
	linkers.EndModify();
	simplified_net.EndModify();

	// For now, just print the SMILES of the nodes and linkers.
	// Eventually, this may become the basis for MOFFLES.
	printFragments(uniqueSMILES(nodes.Separate(), obconv));
	printFragments(uniqueSMILES(linkers.Separate(), obconv));

	if (EXPORT_NODES) {
		writeCIF(&nodes, "Test/nodes.cif");
		writeCIF(&linkers, "Test/linkers.cif");
		writeCIF(&orig_mol, "Test/orig_mol.cif");
		writeCIF(&simplified_net, "Test/condensed_linkers.cif");
	}

	return(0);
}


bool readCIF(OBMol* molp, std::string filepath) {
	// Read the first distinguished molecule from a CIF file
	// (TODO: check behavior of mmcif...)
	OBConversion obconversion;
	obconversion.SetInFormat("mmcif");
	obconversion.AddOption("p", OBConversion::INOPTIONS);
	// Can disable bond detection as a diagnostic:
	// obconversion.AddOption("s", OBConversion::INOPTIONS);
	return obconversion.ReadFile(molp, filepath);
}

void writeCIF(OBMol* molp, std::string filepath, bool write_bonds) {
	// Write a molecule to file
	OBConversion conv;
	conv.SetOutFormat("cif");  // mmcif has extra, incompatible fields
	if (write_bonds) {
		conv.AddOption("g");
	}
	conv.WriteFile(molp, filepath);
}

void printFragments(const std::vector<std::string> &unique_smiles) {
	// Write a list of fragments
	// Use a const_iterator since we're not modifying the vector: http://stackoverflow.com/questions/4890497/how-do-i-iterate-over-a-constant-vector
	for (std::vector<std::string>::const_iterator i2 = unique_smiles.begin(); i2 != unique_smiles.end(); ++i2) {
		printf("%s", i2->c_str());
	}
}

std::vector<std::string> uniqueSMILES(std::vector<OBMol> fragments, OBConversion obconv) {
	// Extracts list of SMILES for unique fragments
	std::vector<std::string> unique_smiles;
	for (std::vector<OBMol>::iterator it = fragments.begin(); it != fragments.end(); ++it) {
		OBMol canon = *it;
		resetBonds(&canon);
		std::string mol_smiles = obconv.WriteString(&canon);
		if (!inVector<std::string>(mol_smiles, unique_smiles)) {
			unique_smiles.push_back(mol_smiles);
		}
	}
	return unique_smiles;
}

bool isMetal(const OBAtom* atom) {
	// Use the InChI definition of metals from https://jcheminf.springeropen.com/articles/10.1186/s13321-015-0068-4
	// Nonmetals are H, He, B, C, N, O, F, Ne, Si, P, S, Cl, Ar, Ge, As, Se, Br, Kr, Te, I, Xe, At, Rn
	const int NUM_NONMETALS = 23;
	unsigned int nonmetals[NUM_NONMETALS] = {1, 2, 5, 6, 7, 8, 9, 10, 14, 15, 16, 17, 18, 32, 33, 34, 35, 36, 52, 53, 54, 85, 86};

	unsigned int element = atom->GetAtomicNum();
	for (int i=0; i<NUM_NONMETALS; ++i) {
		if (nonmetals[i] == element) {
			return false;  // Atom is a nonmetal
		}
	}
	return true;  // Atom not classified as a nonmetal, so it's a metal
}

void resetBonds(OBMol *mol) {
	// Resets bond orders and bond detection for molecular fragments

	// TODO: consider destroying all the bonds and starting from scratch
	// Also see https://sourceforge.net/p/openbabel/mailman/message/6229244/
	// For whatever reason, deleting all the bonds doesn't work out (disconnected fragments, etc.).  Need to diagnose why that's the case.
	// It fails for porphyrins.  I am guessing the cause is that Separate() does not copy over UC information, which is causing problems with PBC.
	// deleteBonds(mol, false);

	mol->BeginModify();
	FOR_ATOMS_OF_MOL(a, *mol) {
		a->SetFormalCharge(0);  // Not a specific reason for doing this, but it doesn't seem to make a difference.
		a->SetSpinMultiplicity(0);  // Reset radicals so that linker SMILES are consistent.
		a->SetHyb(0);  // Also reset hybridization in case that is causing problems
	}
	mol->ConnectTheDots();
	mol->PerceiveBondOrders();
	mol->EndModify();
}

bool subtractMols(OBMol *mol, OBMol *subtracted) {
	// Subtracts all atoms from a second molecule present in the first
	// Returns true if successful, false if failure (extra atoms, etc)
	// Modifies *mol if true, reverts back to original *mol if false
	// This code assumes that the molecule is well-defined (no multiply-defined atoms)

	std::vector<OBAtom*> deleted;  // Consider implementing as a queue
	FOR_ATOMS_OF_MOL(a2, *subtracted) {
		OBAtom* match = atomInOtherMol(&*a2, mol);
		if (!match) {  // *subtracted has an extra atom
			return false;  // *mol not modified
		}
		deleted.push_back(&*match);
	}

	// It's okay to delete the atoms, since they should hold different (cloned) pointers
	mol->BeginModify();
	for (std::vector<OBAtom*>::iterator it = deleted.begin(); it != deleted.end(); ++it) {
		mol->DeleteAtom(*it);
	}
	mol->EndModify();
	return true;
}

int deleteBonds(OBMol *mol, bool only_metals) {
	// Deletes bonds in a molecule, optionally only deleting bonds to metal atoms.
	// Returns the number of bond deletions.
	std::vector<OBMol> fragments;
	obErrorLog.ThrowError(__FUNCTION__, "Bond deletion enabled", obDebug);
	// Same spirit as OBMol::DeleteHydrogens()
	std::vector<OBBond*> delbonds;
	FOR_ATOMS_OF_MOL(a, *mol) {
		if (isMetal(&*a) || !only_metals) {
			FOR_BONDS_OF_ATOM(b, *a) {
				if (!inVector(&*b, delbonds)) {
					// avoid double deletion in the case of metal-metal bonds
					delbonds.push_back(&*b);
				}
			}
		}
	}
	mol->BeginModify();
	std::stringstream deletionMsg;
	for (std::vector<OBBond*>::iterator itb = delbonds.begin(); itb != delbonds.end(); ++itb) {
		deletionMsg << "Deleting bond with atomic numbers ";
		deletionMsg << (*itb)->GetBeginAtom()->GetAtomicNum() << " and ";
		deletionMsg << (*itb)->GetEndAtom()->GetAtomicNum();
		deletionMsg << " (OBBond * " << static_cast<void *>(&*itb) << ")\n";
		mol->DeleteBond(*itb);  // We should also consider preserving the connection point instead of outright deleting the bond
	}
	obErrorLog.ThrowError(__FUNCTION__, deletionMsg.str(), obDebug);
	mol->EndModify();
	return delbonds.size();
}

bool atomsEqual(const OBAtom &atom1, const OBAtom &atom2) {
	// Loosely based on the data copied during OBAtom::Duplicate
	// Atoms are the same if these properties (excluding bond-related) are equivalent
	return atom1.GetAtomicNum() == atom2.GetAtomicNum() &&
			atom1.GetVector().IsApprox(atom2.GetVector(), 1.0e-6) &&
			atom1.GetIsotope() == atom2.GetIsotope();
}

OBAtom* atomInOtherMol(OBAtom *atom, OBMol *mol) {
	// Is an atom within a molecule?  (as defined by atomsEqual conditions)
	// If so, return the pointer of the copycat.  Otherwise, return NULL
	// This has the nice benefit that the usage is also compatible with bool
	// ( if (atomInOtherMol(atomp, molp)) {}  will work, too.)
	FOR_ATOMS_OF_MOL(a, *mol) {
		if (atomsEqual(*a, *atom)) {
			return &*a;
		}
	}
	return NULL;
}

int collapseSBU(OBMol *mol, OBMol *fragment) {
	// Simplifies *mol by combining all atoms from *fragment into a single
	// pseudo-atom, which maintains all connections to other existing atoms.
	// Returns the number of external bonds maintained.

	// Pseudo-code ideas go here:
	// Test if fragment is in mol (and map the atoms.  See subtractMols for help)
	// For each atom in this atom list:
	// 	For each bond in atom
	// 		If the bond is external (contains an atom not in the fragment atom list),
	// 		then save the external atom's pointer for connections at the end.
	//
	// Calculate the centroid of the SBU (external routine.  Will need some work)
	// (for now, the centroid can probably be a stub.  Temporarily, pick the first linker atom).
	// subtractMols(mol, fragment);
	//
	// Make a new atom in mol (pseudo-atom) with the coordinates of the centroid
	// Re-make bonds from the pseudo-atom to existing atoms
	//
	// Return the number of bonds formed
	return 0;
}

vector3 getCentroid(OBMol *fragment, bool weighted) {
	// STUB
	// Calculate the centroid of a fragment, optionally weighted by the atomic mass
	// (which would give the center of mass).  Consider periodicity as needed, and
	// wrap coordinates inside of [0,1].
	// Returns a vector3 of the centroid's coordinates.

	// At first, I thought the periodicity would be even trickier than it is.
	// You do not have to worry about which unit cell you end up in (which would
	// require enumerating the possibilities), but rather you can just calculate
	// it and wrap it to the unit cell at the end.

	// For individual atoms, dwell on what algorithm would make the most sense.
	// Iterating over bonds from the first fragment?  Graph traversal from the
	// first atom in the molecule?  Some shortcut based on PBC calculations?

	// If the fragment is non-periodic, this becomes a much easier case.
	// Handle as a separate "if statement" as in the rest of the code.

	// TODO: currently a stub: return the coordinates of the first atom (check implementation!)
	return fragment->GetAtom(0)->GetVector();
}
